<?php

function module_blocks_theme(): array
{
  return array(
    'mon_module' => array(
      'variables' => array(
        'title' => 'Default title !!!!!',
        'description' => 'desc!'
      ),
      'template' => 'block--mon-module'));
}
/*
function test_db():array{
  $database = \Drupal::database();
  $query = $database->query("SELECT nid FROM node");
  $result = $query->fetchAll();
  return $result;

}
*/
?>
